# Copyright (c) Open Enclave SDK contributors.
# Licensed under the MIT License.

---
- name: Install apt-transport-https APT package
  apt:
    name: apt-transport-https
    state: latest

- name: Add APT repository key
  apt_key:
    url: "{{ apt_key_url }}"
    state: present

- name: Add APT repository
  apt_repository:
    repo: "{{ apt_repository }}"
    state: present
    update_cache: yes
